//------------------------------------------------------------------
//-- File generated by RobustVerilog parser
//-- RobustVerilog version 1.2 (limited free version)
//-- Invoked Sun Mar 24 15:39:38 2019
//-- Source file: prgen_rand.v
//-- Parent file: axi_slave_busy.v
//-- Run directory: E:/vlsi/axi_slave/run/
//-- Target directory: out/
//-- Command flags: ../src/base/axi_slave.v -od out -I ../src/gen -list list.txt -listpath -header -gui 
//-- www.provartec.com/edatools ... info@provartec.com
//------------------------------------------------------------------




  
function integer rand_chance;
      input [31:0] chance_true;

      begin
     if (chance_true > 100)
       begin
          $display("RAND_CHANCE-E-: fatal error, rand_chance called with percent chance larger than 100.\tTime: %0d ns", $time);
          $finish;
       end
     rand_chance = (rand_f(1,100) <= chance_true);
      end
endfunction // rand_chance


function integer rand_f;
      input [31:0] min;
      input [31:0] max;

      integer      range;
      begin
     if (min > max)
       begin
          $display("rand_f-E-: fatal error, rand_f was called with min larger than max.\tTime: %0d ns", $time);
          $finish;
       end

     range = (max - min) + 1;
     if (range == 0) range = -1;
     rand_f  = min + ($random % range); 
      end
endfunction // rand_f


function integer align;
      input [31:0]  num;
      input [31:0]  align_size;
      
      begin
         align = num - (num % align_size);
      end
endfunction


function integer rand_align;
      input [31:0] min;
      input [31:0] max;
      input [31:0] align_val;

      begin
         rand_align = rand_f(min, max);
         
         if (rand_align > align_val)
           rand_align = align(rand_align, align_val);
      end
endfunction



